# Generated by Django 6.0.3 on 2026-03-19 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami noto'g'ri formatda. Iltimos, +998XXXXXXXXX yoki XXXXXXXXX formatida kiriting.", regex='^\\+?998?\\d{9}$|^\\d{9}$')]),
        ),
    ]
