# Generated by Django 6.0.2 on 2026-03-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
