# Generated by Django 6.0.2 on 2026-03-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ai_labels',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
