# Generated by Django 6.0.3 on 2026-03-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location_address',
            field=models.CharField(default='Kiritilmagan', max_length=255),
        ),
    ]
