# Generated by Django 6.0.3 on 2026-03-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location_address',
            field=models.CharField(max_length=255),
        ),
    ]
