# Generated by Django 6.0.3 on 2026-04-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_saveditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='items_m2m', to='items.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='items', to='items.color'),
        ),
    ]
